Renamed program

diff --git a/backup b/backup
--- a/backup
+++ b/backup
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-USE="verity_list -c ... | blacktar_backup [ -s spool_dir ] [ -l limit_bytes ] /key/file s3-bucket"
+USE="verity_list -c ... | verity_backup [ -s spool_dir ] [ -l limit_bytes ] /key/file s3-bucket"
 
 dir=`cd $(dirname $0) && pwd`
 
@@ -20,15 +20,15 @@ mkdir "$tmp/$$"
 
 function s3_put { #s3-bucket-name hash path
 	echo "put: starting $2 $3" >&2
-	hmac=`echo -n "$hash" | "$dir"/../lib/blacktar/hmacs <(echo -n "$passphrase_xxd" | xxd -r) | cut -d ' ' -f 1`
+	hmac=`echo -n "$hash" | "$dir"/../lib/verity-backup/hmacs <(echo -n "$passphrase_xxd" | xxd -r) | cut -d ' ' -f 1`
 	mkdir "$tmp/$$/$2.d"
 	ln -s "$3" "$tmp/$$/$2.d/$2"
 #	noise to osbscure file size
-#	"$dir"/../lib/blacktar/noise "$3" "$tmp/$$/$2.d/noise"
+#	"$dir"/../lib/verity-backup/noise "$3" "$tmp/$$/$2.d/noise"
 	( ls "$tmp/$$/$2.d" | tar chCfT "$tmp/$$/$2.d" - - | gpg -c --force-mdc --batch --no-tty --passphrase-fd 3 3< <(echo -n "$passphrase_xxd" | xxd -r) > "$tmp/$$/$hmac" ) 2> "$tmp/$$/err"
 	if [ `stat -c%s "$tmp/$$/err"` -ne 0 ]; then
 		cat "$tmp/$$/err" >&2
-		echo "blacktar put: aborting on tar|gpg error for $2 $3" >&2
+		echo "verity_backup put: aborting on tar|gpg error for $2 $3" >&2
 		rm -f "$tmp/$$/$hmac"
 		rm -rf "$tmp/$$/$2.d"
 		return 1; fi
@@ -39,12 +39,12 @@ function s3_put { #s3-bucket-name hash path
 	err=`grep -v -e 'gpg: CAST5 encrypted data' -e 'gpg: encrypted with 1 passphrase' "$tmp/$$/err"`
 	if [ "$err" ]; then
 		echo "$err" >&2
-		echo "blacktar put: aborting on gpg|tar pipe error for $2 $3" >&2
+		echo "verity_backup put: aborting on gpg|tar pipe error for $2 $3" >&2
 		rm "$tmp/$$/$hmac"
 		rm -rf "$tmp/$$/$2.d"
 		return 1; fi 
 	if	[ ! -f "$tmp/$$/$2.d/$2" ]; then
-		echo "blacktar verify: missing from archive: $2 ( $3 )" >&2
+		echo "verity_backup verify: missing from archive: $2 ( $3 )" >&2
 		rm "$tmp/$$/$hmac"
 		rm -rf "$tmp/$$/$2.d"
 		return 1; fi
@@ -62,9 +62,9 @@ function s3_put { #s3-bucket-name hash path
 			mkdir -p "$spool_dir"
 			mv -i "$tmp/$$/$hmac" "$spool_dir/$hmac.$md5"
 		else	md5=`echo $md5 | xxd -p -r | openssl enc -base64`
-			blacktar_s3_put "$1/$hmac" filename="$tmp/$$/$hmac" md5="$md5"
+			verity_s3_put "$1/$hmac" filename="$tmp/$$/$hmac" md5="$md5"
 			rm "$tmp/$$/$hmac"
-			echo "$hmac" >> /var/local/cache/blacktar/"$1"
+			echo "$hmac" >> /var/local/cache/verity-backup/"$1"
 			fi
 	echo "put: finished $2 $3" >&2
 	echo "$2$3"; }
@@ -77,15 +77,15 @@ while IFS= read -r -d '' line; do
 	echo -ne \\0 >> "$tmp/$$/stdin-sorted"
 	done < <(sort -uz "$tmp/$$/stdin-buf")
 
-"$dir"/../lib/blacktar/hmacs <(echo -n "$passphrase_xxd" | xxd -r) < "$tmp/$$/hashes.in" | sort -u > "$tmp/$$/hash_lookup_table"
+"$dir"/../lib/verity-backup/hmacs <(echo -n "$passphrase_xxd" | xxd -r) < "$tmp/$$/hashes.in" | sort -u > "$tmp/$$/hash_lookup_table"
 rm "$tmp/$$/hashes.in"
 cut -d ' ' -f 1 < "$tmp/$$/hash_lookup_table" > "$tmp/$$/db"
 
-if	[ ! -f "/var/local/cache/blacktar/$bucket" ]
-	then	blacktar_s3_list_keys "$bucket" | sort -u \
-		> "/var/local/cache/blacktar/$bucket"; fi
+if	[ ! -f "/var/local/cache/verity-backup/$bucket" ]
+	then	verity_s3_list_keys "$bucket" | sort -u \
+		> "/var/local/cache/verity-backup/$bucket"; fi
 
-diff "$tmp/$$/db" <(sort -u "/var/local/cache/blacktar/$bucket") | grep '^<' | cut -c 3- | "$dir"/../lib/blacktar/hashes "$tmp/$$/hash_lookup_table" > "$tmp/$$/diff.hashes"
+diff "$tmp/$$/db" <(sort -u "/var/local/cache/verity-backup/$bucket") | grep '^<' | cut -c 3- | "$dir"/../lib/verity-backup/hashes "$tmp/$$/hash_lookup_table" > "$tmp/$$/diff.hashes"
 rm "$tmp/$$/hash_lookup_table" "$tmp/$$/db"
 if	[ ! -f "$tmp/$$/diff.hashes" ]
 	then rm -rf "$tmp/$$"; exit; fi
@@ -96,7 +96,7 @@ while IFS= read -r -d '' line; do
 	s3_put "$bucket" "$hash" "$path"
 	if	[ "$limit" ]
 		then if	[ "$total" -gt "$limit" ]; then break; fi; fi
-	done < <("$dir"/../lib/blacktar/paths "$tmp/$$/stdin-sorted" < "$tmp/$$/diff.hashes")
+	done < <("$dir"/../lib/verity-backup/paths "$tmp/$$/stdin-sorted" < "$tmp/$$/diff.hashes")
 
 rm -rf "$tmp/$$"
 
diff --git a/retrieve b/retrieve
--- a/retrieve
+++ b/retrieve
@@ -31,12 +31,12 @@ while [ true ]; do
 	err=`grep -v -e 'gpg: CAST5 encrypted data' -e 'gpg: encrypted with 1 passphrase' "$tmp/$$/err"`
 	if [ "$err" ]; then
 		echo "$err" >&2
-		echo "blacktar s3_verify $2: gpg/tar pipeline printed errors, retrying" >&2
+		echo "s3_verify $2: gpg/tar pipeline printed errors, retrying" >&2
 		continue; fi
 	if
 		[ ! -f "$tmp/$$/$$/$4" ]
 		then
-			echo "blacktar s3_verify: failed to extract $2, retrying" >&2
+			echo "s3_verify: failed to extract $2, retrying" >&2
 			continue; fi
 	mv "$tmp/$$/$$/$4" "$3"
 	test_hmac=`sha256sum "$3" | cut -d ' ' -f 1`
@@ -45,7 +45,7 @@ while [ true ]; do
 		then
 			rm -rf "$tmp/$$/$$"
 			rm "$3"
-			echo "blacktar s3_verify: checksum mismatch: $4, retrying" 1>&2
+			echo "s3_verify: checksum mismatch: $4, retrying" 1>&2
 			continue
 		else break; fi
 	done
